{% set name = "goatools" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: c25cb7b6044308d359a010fc55a9b9f2f58dd64e4e2afd181d22d665d781a3dc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - setuptools_scm_git_archive
    - wheel
    - pip
  run:
    - python
    - pandas
    - numpy
    - scipy
    - xlsxwriter
    - statsmodels
    - openpyxl
    - docopt
    - pydot
    - requests

test:
  imports:
    - goatools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/tanghaibao/goatools
  summary: Python scripts to find enrichment of GO terms
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joshuazhuang7
