{% set name = "goatools" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: 6c6e952b287bc9d4554684dc6e3145fa95e97e8e9c28e7a142faf22f68abacdb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - docopt
    - numpy
    - pandas
    - pydot
    - python
    - requests
    - scipy
    - statsmodels
    - xlrd >=1.2.0
    - xlsxwriter

test:
  imports:
    - goatools

about:
  home: http://github.com/tanghaibao/goatools
  summary: Python scripts to find enrichment of GO terms
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
