{% set name = "goatools" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: c25cb7b6044308d359a010fc55a9b9f2f58dd64e4e2afd181d22d665d781a3dc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - docopt
    - numpy
    - pandas
    - pydot
    - python
    - requests
    - scipy
    - statsmodels
    - xlrd >=1.2.0
    - xlsxwriter

test:
  imports:
    - goatools

about:
  home: http://github.com/tanghaibao/goatools
  summary: Python scripts to find enrichment of GO terms
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
