{% set name = "goatools" %}
{% set version = "1.4.12" %}
{% set sha256 = "24a2c5dd7859a4ad4b7dbeff26fed44fc964e57c95b06cd852e4b08f78b097f1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - setuptools
    - pandas
    - numpy
    - scipy
    - statsmodels
    - openpyxl
    - docopt
    - ftpretty
    - pydot
    - requests
    - rich
    - xlsxwriter

test:
  requires:
    - python {{ python_min }}
  imports:
    - goatools
    - goatools.obo_parser
    - goatools.go_enrichment
    - goatools.associations
  commands:
    - find_enrichment.py -h
    - map_to_slim.py -h
    - plot_go_term.py -h

about:
  home: https://github.com/tanghaibao/goatools
  summary: Python library to handle and find enriched Gene Ontology (GO) terms
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pypi.org/project/goatools
  dev_url: https://github.com/tanghaibao/goatools

extra:
  recipe-maintainers:
    - mencian
