{% set name = "goatools" %}
{% set version = "1.3.9" %}
{% set sha256 = "a9c2fe7d4735d725dc685b1d4ef5df489f37506ada1c8198f0786c92559c348c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --use-pep517 -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest
    - setuptools-scm
  run:
    - python >=3.7
    - setuptools
    - pandas
    - numpy
    - scipy
    - statsmodels
    - openpyxl
    - docopt
    - pydot
    - requests
    - xlsxwriter

test:
  imports:
    - goatools
    - goatools.obo_parser
    - goatools.go_enrichment
    - goatools.associations
  commands:
    - find_enrichment.py -h
    - map_to_slim.py -h
    - plot_go_term.py -h

about:
  home: https://github.com/tanghaibao/goatools
  summary: Python library to handle and find enriched Gene Ontology (GO) terms
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pypi.org/project/goatools/

extra:
  recipe-maintainers:
    - mencian
