{% set name = "goatools" %}
{% set version = "1.3.11" %}
{% set sha256 = "008b73e5c2a6d6d6c65246d0ab941c8d841be511a22a1d15ca5bfd0ff6f72230" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goatools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest
    - setuptools-scm
  run:
    - python >=3.7
    - pandas
    - numpy
    - scipy
    - statsmodels
    - openpyxl
    - docopt
    - pydot
    - requests
    - rich
    - xlsxwriter

test:
  imports:
    - goatools
    - goatools.obo_parser
    - goatools.go_enrichment
    - goatools.associations
  commands:
    - find_enrichment.py -h
    - map_to_slim.py -h
    - plot_go_term.py -h

about:
  home: https://github.com/tanghaibao/goatools
  summary: Python library to handle and find enriched Gene Ontology (GO) terms
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pypi.org/project/goatools/

extra:
  recipe-maintainers:
    - mencian
